aplikasi struktur organisasi/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('employee', EmployeeController::class);
Route::resource('company', CompanyController::class);

aplikasi struktur organisasi/app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';
    protected $fillable = [
        'nama',
        'alamat'
    ];
    public function employee(){
        return $this->hasOne('\App\Models\Employee','company_id');
    }
}

aplikasi struktur organisasi/app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
    protected $fillable = [
        'nama',
        'atasan_id',
        'company_id'
    ];

    // public function present_nama_atasan(){
    //     return $this->find($this->atasan_id)->nama;
    // }
    // public function present_nama_company(){
    //     $company = $this->company;
    //     return $company->nama;
    // }
    public function bawahan(){
        return $this->hasMany(self::class,'atasan_id');
    }
    public function atasan(){
        return $this->belongsTo(self::class,'atasan_id');
    }
    public function company(){
        return $this->BelongsTo('App\Models\Company','company_id');
    }
}

aplikasi struktur organisasi/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

aplikasi struktur organisasi/app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Company::all();
        return view('company.index',['company'=>$company]);
    }
    private function _validate(Request $request){
        $validatedData = $request->validate([
            'nama' => 'required|min:2|max:50',
            'alamat' => 'required|min:2|max:50'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = $request->all();
        $this->_validate($request);

        Company::create($company);
        return redirect()->route('company.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('company.edit',['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->_validate($request);
        $company = Company::find($id);
        $company->update($request->all());
        return redirect()->route('company.index')->with('success','Data Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        $company->delete();
        return redirect()->route('company.index')->with('success','Data Berhasil dihapus');
    }
}

aplikasi struktur organisasi/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

aplikasi struktur organisasi/app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;

use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employee = Employee::all();
        // dd($employee->atasan()->nama);
        return view('employee.index',['employee' => $employee]);
    }
    private function _validate(Request $request){
        $validatedData = $request->validate([
            'nama' => 'required|min:2|max:50'
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = Company::all();
        $atasan = Employee::all();
        return view('employee.create',['company' => $company,'atasan' => $atasan]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $all = $request->all();
        $this->_validate($request);
        if ($request->input('atasan_id')=='null') {
            unset($all['atasan_id']);
        }
        Employee::create($all);
        return redirect()->route('employee.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::all();
        $atasan = Employee::all();

        $employee = Employee::find($id);
    return view('employee.edit',['employee' => $employee,'company' => $company,'atasan' => $atasan]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->_validate($request);
        $employee = Employee::find($id);
        if ($all['atasan_id']=='null') {
            unset($all['atasan_id']);
        }
        $employee->update($all);
        return redirect()->route('employee.index')->with('success','Data Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();
        return redirect()->route('employee.index')->with('success','Data Berhasil dihapus');
    }
}

aplikasi struktur organisasi/resources/views/company/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tambah company</title>
</head>

<body>
    <form action="{{ route('company.store') }}" method="POST">
        @csrf
        <label for="">Nama</label>
        <input type="text" name="nama" placeholder="Nama">
        <label for="">Alamat</label>
        <input type="text" name="alamat" placeholder="Alamat">
        <input type="submit" value="simpan">
    </form>
</body>

</html>

aplikasi struktur organisasi/resources/views/company/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>edit company</title>
</head>

<body>
    <form action="{{ route('company.update',$company->id) }}" method="POST">
        @csrf
        <input type="hidden" name="_method" value="put" />
        <label for="">Nama</label>
        <input type="text" name="nama" placeholder="Nama" value="{{$company->nama}}">
        <label for="">Alamat</label>
        <input type="text" name="alamat" placeholder="Alamat" value="{{$company->alamat}}">
        <input type="submit" value="simpan">
    </form>
</body>

</html>

aplikasi struktur organisasi/resources/views/company/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company</title>
</head>

<body>
    @if ($message = Session::get('success'))
        <div style="color: green">{{$message}}</div>
    @endif
    <div>
        <a href="{{ route('company.create') }}">tambah</a>
    </div>

    <table>
        <thead>
            <tr>
                <th>no</th>
                <th>nama</th>
                <th>alamat</th>

                <th>aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($company as $no => $item)
                <tr>
                    <td>{{ $no }}</td>
                    <td>{{ $item->nama }}</td>
                    <td>{{ $item->alamat }}</td>
                    <td>
                        <a href="{{ route('company.edit', $item->id) }}">Edit</a>
                        <form action="{{ route('company.destroy', $item->id) }}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="delete" />
                            <input type="submit" value="Hapus">
                        </form>

                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>

aplikasi struktur organisasi/resources/views/employee/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tambah employee</title>
</head>

<body>
    <form action="{{ route('employee.store') }}" method="POST">
        @csrf
        <label for="">Nama</label>
        <input type="text" name="nama" placeholder="Nama Employee">
        <label for="">Atasan</label>
        <select name="atasan_id" id="atas">
            <option value="null">tidak memiliki atasan</option>
            @foreach ($atasan as $item)
                <option value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <label for="">company</label>
        <select name="company_id" id="atas">
            @foreach ($company as $item)
                <option value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <input type="submit" value="simpan">
    </form>
</body>

</html>

aplikasi struktur organisasi/resources/views/employee/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tambah employee</title>
</head>

<body>
    <form action="{{ route('employee.update',$employee->id) }}" method="POST">
        @csrf
        <input type="hidden" name="_method" value="put" />
        <label for="">Nama</label>
        <input type="text" name="nama" placeholder="Nama Employee" value="{{$employee->nama}}">
        <label for="">Atasan</label>
        <select name="atasan_id" id="atas">
            <option value="null">tidak memiliki atasan</option>
            @foreach ($atasan as $item)
                <option @if ($employee->atasan_id == $item->id)
                    selected
                @endif value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <label for="">company</label>
        <select name="company_id" id="atas">
            @foreach ($company as $item)
                <option @if ($employee->company_id == $item->id)
                    selected
                @endif value="{{ $item->id }}">{{ $item->nama }}</option>
            @endforeach
        </select>
        <input type="submit" value="simpan">
    </form>
</body>

</html>

aplikasi struktur organisasi/resources/views/employee/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>
</head>

<body>
    @if ($message = Session::get('success'))
        <div style="color: green">{{$message}}</div>
    @endif
    <div>
        <a href="{{ route('employee.create') }}">tambah</a>
    </div>

    <table>
        <thead>
            <tr>
                <th>no</th>
                <th>nama</th>
                <th>atasan</th>
                <th>company</th>
                <th>aksi</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($employee as $no => $item)
                <tr>
                    <td>{{ $no }}</td>
                    <td>{{ $item->nama }}</td>
                    @if ($item->atasan)
                        <td>{{ $item->atasan->nama }}</td>
                    @else
                        <td>-</td>
                    @endif
                    <td>{{ $item->company->nama }}</td>
                    <td>
                        <a href="{{ route('employee.edit', $item->id) }}">Edit</a>
                        <form action="{{ route('employee.destroy', $item->id) }}" method="POST">
                            @csrf
                            <input type="hidden" name="_method" value="delete" />
                            <input type="submit" value="Hapus">
                        </form>

                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>